### ISSUE TITLE
Where is the NODE sdk ?

### ISSUE THREAD

**Issue by glococo** [AddonPayments/js-sdk#1]
I'm surprised that JS-SDK Repository is not a JS/Node backend.

Is there any official JS/Node SDK available ?

Cheers

**Comment by glococo** [comment]
Is this the official NODE JS SDK ?

https://github.com/globalpayments/node-sdk

**Comment by VictorACH** [comment]
Good morning @glococo.

The JavaScript SDK is not server-oriented like Node JS.

For Node JS there is the GlobalPayments SDK:
- https://github.com/globalpayments/node-sdk

The JavaScript SDK provided in this repository is for you to implement the payment gateway calls from your web page, it runs from the client.

For this type of query we have Addon Payments support at email soporte@addonpayments.com or telephone +34 914353028 option 2. This support will answer any questions you may have regarding integration and will guide you step-by-step through the installation of your Addon Payments payment gateway.
